pickaxe_stats/config/routes.rb
Rails.application.routes.draw do

  get 'stats/general'
  get 'stats/travel'
  get 'stats/food'
  get 'stats/kills'
  get 'stats/mining'
  get 'stats/crafting'
  get 'stats/achievements'
  get 'stats/adventuring_time'

  resources :players
  resources :weekly_stats

  root to: 'players#index'

  get :dashboard, controller: 'main', action: 'dashboard'

  get 'week/:weekend_number', controller: 'weekly_stats', action: 'most_recent'
end

pickaxe_stats/app/views/layouts/_display_messages.html.haml
.container
  .row
    .col-md-12
      - flash.each do |type, message|
        .alert.fade.in{ class: bootstrap_class_for(type) }
          %button.close{ data: { dismiss: 'alert'} }
            x
          = raw(message)

pickaxe_stats/app/views/layouts/_header.html.haml
.navbar-inverse
  .navbar-header
    %button.navbar-toggle{ type: 'button', data: { toggle: 'collapse', target: '.navbar-collapse' } }
      %span.sr-only
        Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{ href: '/'}
      = image_tag "pickaxe_club_logo.png", alt: 'Pickaxe Club Stats'
  .collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right#fix-me
      %li
        = link_to dashboard_path do
          %i.fa.fa-sun-o
          Dashboard
      %li
        = link_to players_path do
          Players
      %li
        = link_to weekly_stats_path do
          Weekends
      %li
        = link_to stats_general_path do
          General
      %li
        = link_to stats_travel_path do
          Travel
      %li
        = link_to stats_food_path do
          Food
      %li
        = link_to stats_kills_path do
          Kills
      %li
        = link_to stats_crafting_path do
          Crafting
      %li
        = link_to stats_achievements_path do
          Achievements
      %li
        = link_to stats_adventuring_time_path do
          Adventuring Time

pickaxe_stats/app/views/layouts/_user_navbar_preference.html.haml
- if user_signed_in? && current_user.navbar_preference == 'not fixed' || !user_signed_in?
  .navbar.navbar-default{role: 'navigation'}
    = render partial: "layouts/header"
- else
  .navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
    = render partial: "layouts/header"

pickaxe_stats/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pickaxe Club Stats
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .navbar.navbar-default{role: 'navigation'}
      = render partial: 'layouts/header'
    .wrapper
      = render partial: 'layouts/display_messages'
      = yield