pickaxe_stats/config/routes.rb
Rails.application.routes.draw do

  get 'stats/general'
  get 'stats/travel'
  get 'stats/food'
  get 'stats/kills'
  get 'stats/mining'
  get 'stats/crafting'
  get 'stats/achievements'
  get 'stats/adventuring_time'

  resources :players
  resources :weekly_stats

  root to: 'players#index'

  get :dashboard, controller: 'main', action: 'dashboard'

  get 'week/:weekend_number', controller: 'weekly_stats', action: 'most_recent'
end

pickaxe_stats/app/models/weekly_stat.rb
# == Schema Information
#
# Table name: weekly_stats
#
#  id             :bigint(8)        not null, primary key
#  commit_date    :datetime         not null
#  launched_at    :datetime
#  message        :string
#  notes          :string
#  player_count   :integer          default(0), not null
#  sha            :string           not null
#  shutdown_at    :datetime
#  title          :string
#  week_number    :integer          not null
#  weekend_number :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class WeeklyStat < ApplicationRecord
  has_many :stats
end

pickaxe_stats/app/controllers/weekly_stats_controller.rb
class WeeklyStatsController < ApplicationController
  before_action :set_weekly_stat, only: [:show, :edit, :update, :destroy]

  # GET /weekly_stats
  # GET /weekly_stats.json
  def index
    @weekly_stats = WeeklyStat.all.order(commit_date: :desc)
  end

  # GET /weekly_stats/1
  # GET /weekly_stats/1.json
  def show
  end

  # GET /weekly_stats/new
  def new
    @weekly_stat = WeeklyStat.new
  end

  # GET /weekly_stats/1/edit
  def edit
  end

  # POST /weekly_stats
  # POST /weekly_stats.json
  def create
    @weekly_stat = WeeklyStat.new(weekly_stat_params)

    respond_to do |format|
      if @weekly_stat.save
        format.html { redirect_to @weekly_stat, notice: 'Weekly stat was successfully created.' }
        format.json { render :show, status: :created, location: @weekly_stat }
      else
        format.html { render :new }
        format.json { render json: @weekly_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekly_stats/1
  # PATCH/PUT /weekly_stats/1.json
  def update
    respond_to do |format|
      if @weekly_stat.update(weekly_stat_params)
        format.html { redirect_to weekly_stats_path, notice: 'Weekly stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekly_stat }
      else
        format.html { render :edit }
        format.json { render json: @weekly_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_stats/1
  # DELETE /weekly_stats/1.json
  def destroy
    @weekly_stat.destroy
    respond_to do |format|
      format.html { redirect_to weekly_stats_url, notice: 'Weekly stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  def most_recent
    @weekly_stat = WeeklyStat.where(weekend_number: params[:weekend_number]).first
    redirect_to @weekly_stat
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekly_stat
      @weekly_stat = WeeklyStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weekly_stat_params
      params.require(:weekly_stat).permit(:week_number, :weekend_number, :launched_at, :shutdown_at)
    end
end

pickaxe_stats/app/helpers/weekly_stats_helper.rb
module WeeklyStatsHelper
end

pickaxe_stats/app/views/weekly_stats/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@weekly_stat) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :week_number
    = f.input :weekend_number
    = f.input :launched_at
    = f.input :shutdown_at

  .form-actions
    = f.button :submit, class: 'button'

pickaxe_stats/app/views/weekly_stats/edit.html.haml
.container
  .row
    .col-md-12
      %h1 Editing weekly_stat
  .row
    .col-md-12
      = render 'form'
  .row
    .col-md-12
      = link_to 'Show', @weekly_stat
      \|
      = link_to 'Back', weekly_stats_path

pickaxe_stats/app/views/weekly_stats/index.html.haml
.container
  .row
    .col-md-12
      %h1 Listing weekly_stats
  .row
    .col-md-12
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th
              Weekend
              %th
                Launched
              %th
                Shutdown
              %th
                Up for
              %th
                Commit Date
              %th
                Message
              %th Actions
          %tbody
            - @weekly_stats.each do |weekly_stat|
              %tr
                %td.text-center
                  = link_to weekly_stat.weekend_number, weekly_stat
                %td
                  = display_short_date weekly_stat.launched_at
                %td
                  = display_short_date weekly_stat.shutdown_at
                %td
                  - unless weekly_stat.shutdown_at.nil? || weekly_stat.launched_at.nil?
                    = display_stat_time((weekly_stat.shutdown_at - weekly_stat.launched_at) * 20)
                %td
                  = display_short_date weekly_stat.commit_date
                %td
                  = weekly_stat.message
                %td
                  = link_to edit_weekly_stat_path(weekly_stat) do
                    %i.fa.fa-pencil

pickaxe_stats/app/views/weekly_stats/new.html.haml
%h1 New weekly_stat

= render 'form'

= link_to 'Back', weekly_stats_path

pickaxe_stats/app/views/weekly_stats/show.html.haml
.container
  .row
    .col-md-12
      %h1
        Weekend #
        = @weekly_stat.weekend_number
      %br
        = display_short_date @weekly_stat.launched_at
        to
        = display_short_date @weekly_stat.shutdown_at