pickaxe_stats/config/routes.rb
Rails.application.routes.draw do

  get 'stats/general'
  get 'stats/travel'
  get 'stats/food'
  get 'stats/kills'
  get 'stats/mining'
  get 'stats/crafting'
  get 'stats/achievements'
  get 'stats/adventuring_time'

  resources :players
  resources :weekly_stats

  root to: 'players#index'

  get :dashboard, controller: 'main', action: 'dashboard'

  get 'week/:weekend_number', controller: 'weekly_stats', action: 'most_recent'
end

pickaxe_stats/app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                        :bigint(8)        not null, primary key
#  name                      :string           not null
#  uuid                      :string           not null
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  first_seen_weekly_stat_id :integer          not null
#  last_seen_weekly_stat_id  :integer          not null
#

class Player < ApplicationRecord
  belongs_to :first_seen, class_name: "WeeklyStat", foreign_key: "first_seen_weekly_stat_id"
  belongs_to :last_seen, class_name: "WeeklyStat", foreign_key: "last_seen_weekly_stat_id"

  has_many :stats

  has_many :weekly_stats, through: :stats
  
  def stats_for_week_of week_number
    stats = Stat.joins(:weekly_stat).where(stats: {player_id: self.id},
                                           weekly_stats: {week_number: week_number})
  end

  def stats_for stat_key
    stat = Stat.where(player_id: self.id, stat_key: stat_key).
             joins(:week).
             order("weekly_stats.commit_date desc")
  end

  def stat_for_week_of stat_key, week_number
    stat = Stat.joins(:weekly_stat).where(stats: {player_id: self.id,
                                                   stat_key: stat_key
                                               },
                                          weekly_stats: {week_number: week_number}).first
  end

  def stat_for_current stat_key
    most_recent_week = WeeklyStat.joins(:stats).
                            order(commit_date: :desc).
                            where(stats: { player_id: self.id,
                                           stat_key: stat_key}).first

    stat = most_recent_week.stats.
             where(stats: { player_id: self.id, stat_key: stat_key}).first

  end

  def stat_for_previous stat_key
    prev_most_recent_week = WeeklyStat.joins(:stats).
                              order(commit_date: :desc).
                              where(stats: { player_id: self.id,
                                             stat_key: stat_key}).second

    stat = prev_most_recent_week.stats.
             where(stats: { player_id: self.id, stat_key: stat_key}).first

  end

  def stat_delta stat_key
    current = stat_for_current stat_key
    previous = stat_for_previous stat_key

    current.formated_value - previous.formated_value 
  end

end

pickaxe_stats/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.fetch(:player, {})
    end
end

pickaxe_stats/app/helpers/players_helper.rb
module PlayersHelper
end

pickaxe_stats/app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pickaxe_stats/app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

pickaxe_stats/app/views/players/index.html.haml
.container
  .row
    %h1 Players
  .row
    %table.table.table-stripped.table-hover
      %thead
        %tr
          %th
            Name
          %th
            First week seen
          %th
            Last week seen
          %th
            Actions
      %tbody
        - @players.all.order("lower(name)").each do |player|
          %tr
            %td= link_to player.name, player
            %td
              = player.first_seen.week_number unless player.first_seen.nil?
            %td
              = player.last_seen.week_number unless player.last_seen.nil?
            %td
              = link_to edit_player_path(player) do
                %i.fa.fa-pencil
                Edit

pickaxe_stats/app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

pickaxe_stats/app/views/players/show.html.haml
.container
  .row
    .col-md-12
      %h1
        = "#{@player.name}'s Stats!"
  .row
    .col-md-3
      .panel.panel-default
        .panel-heading
          %h3
            %strong
              Total Time Played
        .panel.body
          %h3.text-center
            = display_stat_time @player.stat_for_current('stat.playOneMinute').stat_value
    .col-md-3
      .panel.panel-default
        .panel-heading
          %h3
            %strong
              Last Weekend
              %br
              Time Played
        .panel.body
          %h3.text-center
            = display_stat_time @player.stat_for_current('stat.playOneMinute').stat_delta
  .row
    .col-md-12
      %h3
        %strong
          General
      %table.table.table-bordered.table-hover.table-striped
        %thead
          %tr
            %th
              Weekend
            - GENERAL_STATS_KEYS.each do |key|
              %th
                = key.gsub('stat.','').titlecase
        %tbody
          - WeeklyStat.order(commit_date: :desc).each do |ws|
            %tr
              %td.text-center
                = link_to weekly_stat_path(ws) do
                  = ws.weekend_number || ws.week_number
              - GENERAL_STATS_KEYS.each do |key|
                - stat = Stat.where(weekly_stat_id: ws.id, player_id: @player.id, stat_key: key).first
                %td.text-right
                  = display_stat_value(stat.stat_key, stat.stat_value) unless stat.nil?
                  %br
                  - unless stat.nil?
                    - if stat.stat_delta > 0
                      .text-success
                        %i.fa.fa-arrow-up
                        = "#{display_stat_value(stat.stat_key, stat.stat_delta)}"
                    - elsif stat.stat_delta < 0
                      .text-danger
                        %i.fa.fa-arrow-down
                          = "#{display_stat_value(stat.stat_key, stat.stat_delta)}"
                    - else
                      .text-secondary
                        = "--"

  .row
    .col-md-12
      = link_to 'Edit', edit_player_path(@player)
      |
      = link_to 'Back', players_path